debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.teamhw.opensurveyservice: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: gyanni
    password: thisisTESTpw!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # 테스트용 데이터베이스를 만들 수 있음
    hibernate:
      ddl-auto: create # DDL을 자동으로 생성해줌
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    h2.console.enabled: false
    sql.init.mode: always
    # thymeleaf.cache: false
    data.rest:
      base-path: /api
      detection-strategy: annotated

---
# yml 파일은 '---'를 기준으로 한 페이지에 문서를 여러개 만들 수 있따.
# 다음은 test용 db에 관한 yml 문서이다.

spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mpde=mysql
    driver-class-name: org.h2.Driver
  sql.init.mode: always
  test.database.replace: none
